2021-02-11 13:34:51 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - ENGINE_EVENT - Starting initialization of resources [io_manager, snowflake].
2021-02-11 13:34:51 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - ENGINE_EVENT - Finished initialization of resources [io_manager, snowflake].
2021-02-11 13:34:51 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - PIPELINE_START - Started execution of pipeline "load_data_to_dw_pipeline".
2021-02-11 13:34:51 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - ENGINE_EVENT - Executing steps in process (pid: 98398)
2021-02-11 13:34:51 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - launch_snowpipe - STEP_START - Started execution of step "launch_snowpipe".
2021-02-11 13:34:52 - dagster - INFO - resource:snowflake - 468ca035-2e23-4f46-bda9-235b104c3530 - Executing query: alter pipe gdelt_events_pipe refresh;
2021-02-11 13:34:53 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - launch_snowpipe - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
2021-02-11 13:34:53 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - launch_snowpipe - HANDLED_OUTPUT - Handled output "result" using output manager "io_manager"
2021-02-11 13:34:53 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - launch_snowpipe - STEP_SUCCESS - Finished execution of step "launch_snowpipe" in 2.18s.
2021-02-11 13:34:53 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - run_dbt_transformation - STEP_START - Started execution of step "run_dbt_transformation".
/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/core/definitions/decorators/solid.py:227: ExperimentalWarning: "dbt_cli_run" is an experimental function. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  result = fn(context, **kwargs)
2021-02-11 13:34:53 - dagster - INFO - system - 468ca035-2e23-4f46-bda9-235b104c3530 - run_dbt_transformation - Executing command: dbt --log-format json run --project-dir /Users/olivierdupuis/Git/dio/orchestration/../dw --profiles-dir ~/.dbt
pyenv: dbt: command not found

The `dbt' command exists in these Python versions:
  3.7.4/envs/venv_dio_dw
  3.7.4/envs/venv_footballindex
  3.7.4/envs/venv_format
  3.7.4/envs/venv_ra_fw
  3.7.4/envs/venv_rixo
  venv_dio_dw
  venv_footballindex
  venv_format
  venv_ra_fw
  venv_rixo

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
2021-02-11 13:34:53 - dagster - INFO - system - 468ca035-2e23-4f46-bda9-235b104c3530 - run_dbt_transformation - dbt exited with return code 127
2021-02-11 13:34:53 - dagster - ERROR - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - run_dbt_transformation - STEP_FAILURE - Execution of step "run_dbt_transformation" failed.

dagster.check.CheckError: node not present in dictionary {'status': 'success', 'timing': [{'name': 'compile', 'started_at': '2021-02-10T19:59:58.967751Z', 'completed_at': '2021-02-10T19:59:58.985318Z'}, {'name': 'execute', 'started_at': '2021-02-10T19:59:58.985513Z', 'completed_at': '2021-02-10T20:00:00.045859Z'}], 'thread_id': 'Thread-1', 'execution_time': 1.2482950687408447, 'message': 'SUCCESS 1', 'adapter_response': {'code': 'SUCCESS', 'rows_affected': 1}, 'unique_id': 'model.dio_dw.stg_gdelt_events'}

Stack Trace:
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/core/errors.py", line 182, in user_code_error_boundary
    yield
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/utils/__init__.py", line 355, in iterate_with_context
    next_output = next(iterator)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/core/execution/plan/compute.py", line 104, in execute_core_compute
    for step_output in _yield_compute_results(compute_context, inputs, compute_fn):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/core/execution/plan/compute.py", line 70, in _yield_compute_results
    for event in user_event_sequence:
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/core/definitions/decorators/solid.py", line 230, in compute
    yield from result
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster_dbt/cli/solids.py", line 195, in dbt_cli_run
    cli_output = DbtCliOutput.from_dict(cli_output_dict)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster_dbt/cli/types.py", line 83, in from_dict
    result=DbtResult.from_dict(d),
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster_dbt/types.py", line 169, in from_dict
    results = [NodeResult.from_dict(d) for d in check.is_list(d["results"], of_type=Dict)]
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster_dbt/types.py", line 169, in <listcomp>
    results = [NodeResult.from_dict(d) for d in check.is_list(d["results"], of_type=Dict)]
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster_dbt/types.py", line 102, in from_dict
    node = check.dict_elem(d, "node")
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/check/__init__.py", line 776, in dict_elem
    CheckError("{key} not present in dictionary {ddict}".format(key=key, ddict=ddict))
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)

2021-02-11 13:34:53 - dagster - ERROR - system - 468ca035-2e23-4f46-bda9-235b104c3530 - test_dbt_transformation - Dependencies for step test_dbt_transformation failed: ['run_dbt_transformation']. Not executing.
2021-02-11 13:34:53 - dagster - DEBUG - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - ENGINE_EVENT - Finished steps in process (pid: 98398) in 2.48s
2021-02-11 13:34:53 - dagster - ERROR - load_data_to_dw_pipeline - 468ca035-2e23-4f46-bda9-235b104c3530 - 98398 - PIPELINE_FAILURE - Execution of pipeline "load_data_to_dw_pipeline" failed. Steps failed: ['run_dbt_transformation'].
2021-02-11 14:56:01 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - ENGINE_EVENT - Starting initialization of resources [io_manager, snowflake].
2021-02-11 14:56:01 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - ENGINE_EVENT - Finished initialization of resources [io_manager, snowflake].
2021-02-11 14:56:01 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - PIPELINE_START - Started execution of pipeline "load_data_to_dw_pipeline".
2021-02-11 14:56:01 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - ENGINE_EVENT - Executing steps in process (pid: 8867)
2021-02-11 14:56:01 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - launch_snowpipe - STEP_START - Started execution of step "launch_snowpipe".
2021-02-11 14:56:02 - dagster - INFO - resource:snowflake - a0e6616b-1630-49d2-a4b0-cb671b572626 - Executing query: alter pipe gdelt_events_pipe refresh;
2021-02-11 14:56:03 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - launch_snowpipe - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
2021-02-11 14:56:03 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - launch_snowpipe - HANDLED_OUTPUT - Handled output "result" using output manager "io_manager"
2021-02-11 14:56:03 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - launch_snowpipe - STEP_SUCCESS - Finished execution of step "launch_snowpipe" in 1.78s.
2021-02-11 14:56:03 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - run_dbt_transformation - STEP_START - Started execution of step "run_dbt_transformation".
/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/core/definitions/decorators/solid.py:227: ExperimentalWarning: "dbt_cli_run" is an experimental function. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  result = fn(context, **kwargs)
2021-02-11 14:56:03 - dagster - INFO - system - a0e6616b-1630-49d2-a4b0-cb671b572626 - run_dbt_transformation - Executing command: dbt --log-format json run --profiles-dir ~/.dbt --project-dir /Users/olivierdupuis/Git/dio/orchestration/../dw
pyenv: dbt: command not found

The `dbt' command exists in these Python versions:
  3.7.4/envs/venv_dio_dw
  3.7.4/envs/venv_footballindex
  3.7.4/envs/venv_format
  3.7.4/envs/venv_ra_fw
  3.7.4/envs/venv_rixo
  venv_dio_dw
  venv_footballindex
  venv_format
  venv_ra_fw
  venv_rixo

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
2021-02-11 14:56:03 - dagster - INFO - system - a0e6616b-1630-49d2-a4b0-cb671b572626 - run_dbt_transformation - dbt exited with return code 127
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - run_dbt_transformation - STEP_MATERIALIZATION - dbt node: model.dio_dw.stg_gdelt_events
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - run_dbt_transformation - STEP_MATERIALIZATION - dbt node: model.dio_dw.int_events
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - run_dbt_transformation - STEP_MATERIALIZATION - dbt node: model.dio_dw.wh_events_fact
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - run_dbt_transformation - STEP_MATERIALIZATION - Output from the CLI execution of `dbt run`.
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - run_dbt_transformation - STEP_OUTPUT - Yielded output "dbt_output" of type "DbtCliOutput". (Type check passed).
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - run_dbt_transformation - HANDLED_OUTPUT - Handled output "dbt_output" using output manager "io_manager"
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - run_dbt_transformation - STEP_SUCCESS - Finished execution of step "run_dbt_transformation" in 264ms.
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - test_dbt_transformation - STEP_START - Started execution of step "test_dbt_transformation".
/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dio_orchestration/lib/python3.7/site-packages/dagster/core/definitions/decorators/solid.py:227: ExperimentalWarning: "dbt_cli_test" is an experimental function. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  result = fn(context, **kwargs)
2021-02-11 14:56:04 - dagster - INFO - system - a0e6616b-1630-49d2-a4b0-cb671b572626 - test_dbt_transformation - Executing command: dbt --log-format json test --profiles-dir ~/.dbt --project-dir /Users/olivierdupuis/Git/dio/orchestration/../dw
pyenv: dbt: command not found

The `dbt' command exists in these Python versions:
  3.7.4/envs/venv_dio_dw
  3.7.4/envs/venv_footballindex
  3.7.4/envs/venv_format
  3.7.4/envs/venv_ra_fw
  3.7.4/envs/venv_rixo
  venv_dio_dw
  venv_footballindex
  venv_format
  venv_ra_fw
  venv_rixo

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
2021-02-11 14:56:04 - dagster - INFO - system - a0e6616b-1630-49d2-a4b0-cb671b572626 - test_dbt_transformation - dbt exited with return code 127
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - test_dbt_transformation - STEP_MATERIALIZATION - Output from the CLI execution of `dbt test`.
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - test_dbt_transformation - STEP_OUTPUT - Yielded output "dbt_output" of type "DbtCliOutput". (Type check passed).
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - test_dbt_transformation - HANDLED_OUTPUT - Handled output "dbt_output" using output manager "io_manager"
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - test_dbt_transformation - STEP_SUCCESS - Finished execution of step "test_dbt_transformation" in 209ms.
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - ENGINE_EVENT - Finished steps in process (pid: 8867) in 2.42s
2021-02-11 14:56:04 - dagster - DEBUG - load_data_to_dw_pipeline - a0e6616b-1630-49d2-a4b0-cb671b572626 - 8867 - PIPELINE_SUCCESS - Finished execution of pipeline "load_data_to_dw_pipeline".
